--
--                            U N C L A S S I F I E D
--
--  *=========================================================================*
--  |                                                                         |
--  |                         Manned Flight Simulator                         |
--  |                Naval Air Warfare Center Aircraft Division               |
--  |                        Patuxent River, Maryland                         |
--  |                                                                         |
--  *=========================================================================*
--
------------------------------------------------------------------------------
--
-- PACKAGE NAME     : DG_Host_Specific
--
-- FILE NAME        : DG_Host_Specific_.ada
--
-- PROJECT          : Ada Distributed Interactive Simulation (ADIS)
--                    DIS Gateway (DG) CSCI
--
-- AUTHOR           : B. Dufault - J. F. Taylor, Inc.
--
-- ORIGINATION DATE : August 29, 1994
--
-- PURPOSE:
--   - This package contains routines to do any conversions (such as floating
--     point format, little/big-endian byte ordering, etc.) required by the
--     host machine.
--
-- EFFECTS:
--   - The expected usage is:
--     1. Translate_Net_To_Host should be called for each PDU received from
--        the network.
--     2. Translate_Host_To_Net should be called for each PDU prior to
--        transmitting it on the network.
--
-- EXCEPTIONS:
--   - None.
--
-- PORTABILITY ISSUES:
--   - None.
--
-- ANTICIPATED CHANGES:
--   - None.
--
------------------------------------------------------------------------------

with DG_Generic_PDU,
     DG_Status;

package DG_Host_Specific is

   ---------------------------------------------------------------------------
   -- Translate_Net_To_Host
   ---------------------------------------------------------------------------
   -- Purpose: Performs any conversions necessary to make a PDU received from
   --          the network usable by the host.
   ---------------------------------------------------------------------------

   procedure Translate_Net_To_Host(
      PDU    : in out DG_Generic_PDU.GENERIC_PDU_POINTER_TYPE;
      Status :    out DG_Status.STATUS_TYPE);

   ---------------------------------------------------------------------------
   -- Translate_Host_To_Net
   ---------------------------------------------------------------------------
   -- Purpose: Performs any conversions necessary to make a PDU generated by
   --          the host compatible with the network specification.
   ---------------------------------------------------------------------------

   procedure Translate_Host_To_Net(
      PDU    : in out DG_Generic_PDU.GENERIC_PDU_POINTER_TYPE;
      Status :    out DG_Status.STATUS_TYPE);

end DG_Host_Specific;

------------------------------------------------------------------------------
--
-- MODIFICATION HISTORY:
--
------------------------------------------------------------------------------
